Referring the youtube tutorial by deeplizard [Neural Network Programming - Deep Learning with PyTorch](https://www.youtube.com/playlist?list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG)

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.0.1.post2


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'9.0.176'

# Using CUDA

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

Runs the tensor on GPU instead of CPU

In [6]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

# Tensors Explained - Data Structures of Deep Learning

## Shape

In [7]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
type(t)

torch.Tensor

In [10]:
t.shape

torch.Size([3, 3])

In [11]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [13]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [14]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

## Create tensor importing data

In [15]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [16]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [17]:
torch.tensor(data)

tensor([1, 2, 3])

In [18]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [19]:
torch.from_numpy(data)

tensor([1, 2, 3])

## Creation of tensor without data

In [20]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [21]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [22]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [23]:
torch.rand(2,2)

tensor([[0.2553, 0.0328],
        [0.6384, 0.4398]])

## Memory: Sharing vs Copying

In [24]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [25]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [26]:
data[0] = 0
data[1] = 0
data[2] = 0

In [27]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [28]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


## Reshaping

In [29]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)

In [30]:
t.size() #function

torch.Size([3, 4])

In [31]:
t.shape #attribute

torch.Size([3, 4])

In [32]:
len(t.shape) # Rank of Tensor

2

In [33]:
torch.tensor(t.shape).prod() 
# Convert shape into tensor and then take product of all values in tensor

tensor(12)

In [34]:
# number of elements
t.numel()

12

In [35]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [36]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [37]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [38]:
t1 = t.reshape(1,12)
print(t.shape)
print(t1.shape)

torch.Size([3, 4])
torch.Size([1, 12])


In [39]:
t1 = t1.squeeze()
print(t1.shape)

torch.Size([12])


In [40]:
t1 = t1.unsqueeze(dim =0)
print(t1.shape)

torch.Size([1, 12])


In [41]:
def flatten(t):
    t =t.reshape(1,-1) # -1 indicates that it can be used for any arbitary dimension
    t = t.squeeze()
    return t

In [42]:
flatten(t) #Reshape and Squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [43]:
t.reshape(1,12) # Only Reshape

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [44]:
t.reshape(1,12)[0] #Reshape and Squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

### Concatenation

In [45]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [46]:
torch.cat((t1,t2))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [47]:
torch.cat((t1,t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [48]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

t4 = torch.tensor([
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4]
])

In [49]:
t = torch.stack((t1,t2,t3))

In [50]:
print(t.shape)
t

torch.Size([3, 4, 4])


tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

Add axis for color channel as CNN expects batch+color channel + height and width

In [51]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [52]:
t[0] #first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [53]:
t[0][0] # first color channel

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [54]:
t[0][0][0] # first row of pixels in the first color channel of the first image

tensor([1, 1, 1, 1])

In [55]:
t[0][0][0][0] # first value in the first row of the first color channel of the first image

tensor(1)

In [56]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [57]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [58]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [59]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [60]:
# To flatten individual batches which is useful for CNN
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [61]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

## Element-wise tensor operations

In [62]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [63]:
# Two tensors must have the same shape for element-wise operations
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

### Argmax and Reduction Operations

In [64]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [65]:
t.sum() # Similarly prod, mean, std

tensor(8.)

In [66]:
t.numel()

9

In [67]:
t.sum().numel()

1

In [68]:
t.sum().numel()<t.numel()

True

In [69]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
], dtype = torch.float32)

In [70]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [71]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [72]:
t[0]

tensor([1., 1., 1., 1.])

In [73]:
t[1]

tensor([2., 2., 2., 2.])

In [74]:
t[2]

tensor([3., 3., 3., 3.])

In [75]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

In [76]:
t[0].sum()

tensor(4.)

In [77]:
t[1].sum()

tensor(8.)

In [78]:
t[2].sum()

tensor(12.)

 ### Argmax and Max

In [79]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype = torch.float32)

In [80]:
t.max()

tensor(5.)

In [81]:
t.argmax() # gives indice of max number as if it was flatten

tensor(11)

In [82]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [83]:
t.max(dim=0)

(tensor([4., 3., 3., 5.]), tensor([2, 1, 1, 2]))

In [84]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [85]:
t.max(dim=1)

(tensor([2., 3., 5.]), tensor([3, 2, 3]))

In [86]:
t.argmax(dim=1)

tensor([3, 2, 3])

Argmax is used in the last layer for classification in practice

In [87]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype = torch.float32)

In [88]:
t.mean()

tensor(5.)

In [89]:
t.mean().item()

5.0

In [90]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [92]:
t.mean(dim=1).numpy()

array([2., 5., 8.], dtype=float32)