Referring the youtube tutorial by deeplizard [Neural Network Programming - Deep Learning with PyTorch](https://www.youtube.com/playlist?list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG)

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.0.1.post2


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'9.0.176'

# Using CUDA

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

Runs the tensor on GPU instead of CPU

In [6]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

# Tensors Explained - Data Structures of Deep Learning

## Shape

In [7]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
type(t)

torch.Tensor

In [10]:
t.shape

torch.Size([3, 3])

In [11]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [13]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [17]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

## Create tensor importing data

In [18]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [19]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [20]:
torch.tensor(data)

tensor([1, 2, 3])

In [21]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [22]:
torch.from_numpy(data)

tensor([1, 2, 3])

## Creation of tensor without data

In [23]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [24]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [25]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [26]:
torch.rand(2,2)

tensor([[0.2197, 0.5254],
        [0.3453, 0.1393]])

## Memory: Sharing vs Copying

In [28]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [29]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [30]:
data[0] = 0
data[1] = 0
data[2] = 0

In [31]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [32]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


## Reshaping

In [33]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)

In [34]:
t.size() #function

torch.Size([3, 4])

In [37]:
t.shape #attribute

torch.Size([3, 4])

In [38]:
len(t.shape) # Rank of Tensor

2

In [39]:
torch.tensor(t.shape).prod() 
# Convert shape into tensor and then take product of all values in tensor

tensor(12)

In [40]:
# number of elements
t.numel()

12

In [41]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [42]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [43]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [49]:
t1 = t.reshape(1,12)
print(t.shape)
print(t1.shape)

torch.Size([3, 4])
torch.Size([1, 12])


In [50]:
t1 = t1.squeeze()
print(t1.shape)

torch.Size([12])


In [51]:
t1 = t1.unsqueeze(dim =0)
print(t1.shape)

torch.Size([1, 12])


In [52]:
def flatten(t):
    t =t.reshape(1,-1) # -1 indicates that it can be used for any arbitary dimension
    t = t.squeeze()
    return t

In [53]:
flatten(t) #Reshape and Squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [54]:
t.reshape(1,12) # Only Reshape

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [55]:
t.reshape(1,12)[0] #Reshape and Squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

### Concatenation

In [57]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [58]:
torch.cat((t1,t2))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [59]:
torch.cat((t1,t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [62]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

t4 = torch.tensor([
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4]
])

In [63]:
t = torch.stack((t1,t2,t3))

In [65]:
print(t.shape)
t

torch.Size([3, 4, 4])


tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

Add axis for color channel as CNN expects batch+color channel + height and width

In [66]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [67]:
t[0] #first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [68]:
t[0][0] # first color channel

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [69]:
t[0][0][0] # first row of pixels in the first color channel of the first image

tensor([1, 1, 1, 1])

In [70]:
t[0][0][0][0] # first value in the first row of the first color channel of the first image

tensor(1)

In [71]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [72]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [73]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [74]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [75]:
# To flatten individual batches which is useful for CNN
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [76]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])